# Generated by Django 3.0.5 on 2020-05-20 13:59

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=stdimage.models.StdImageField(upload_to='images/'),
        ),
    ]
