# Generated by Django 3.0.2 on 2020-02-03 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paintlevel', models.CharField(choices=[('basic', 'Basic'), ('tabletop', 'Table Top'), ('display', 'Display')], default='basic', max_length=15)),
                ('paintnum', models.IntegerField()),
                ('build', models.BooleanField()),
                ('base', models.BooleanField()),
                ('comments', models.CharField(max_length=2000)),
                ('basetype', models.CharField(choices=[('sand', 'Sand'), ('mud', 'Mud'), ('concrete', 'Concrete'), ('grass', 'Grass'), ('rubble', 'Rubble'), ('snow', 'Snow'), ('none', 'None')], default='none', max_length=15)),
                ('scheme', models.CharField(max_length=500)),
                ('adnum', models.CharField(max_length=60)),
                ('adfirstline', models.CharField(max_length=100)),
                ('adtown', models.CharField(max_length=70)),
                ('adpostcode', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
