# Generated by Django 3.0.5 on 2020-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200418_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_form',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('painted', 'Painting Complete'), ('basing', 'Basing Complete'), ('finishing', 'Final Touches'), ('complete', 'Waiting To Be Shipped'), ('shipped', 'Shipped')], default='ordered', max_length=30),
        ),
    ]
