# Generated by Django 3.0.5 on 2020-05-05 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200505_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='orderdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
