# Generated by Django 3.0.5 on 2020-06-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
