# Generated by Django 3.0.5 on 2020-06-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200630_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
